# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9fa98d4499394e7344e916d86db7c1822fe6e0e45ef9b12b10d8d56d64b0c55a6e63deaafb5b66eb7a39ebf9c8027a5947aa58e6f3e01eda67937a34a2023253

test:
  secret_key_base: 7af88346f935f10874f984d15759dbd491be9020f6ba77a97d5770aeab89fd08e4137b73d19200cc7d8a8440800affca3db1071198244283a4566f5ef1ccba27

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
